### PR TITLE
Updating Dependencies +

### PR DESCRIPTION
**Pull request by paul90**
**This pull request change contains a breaking change**

We move the views subdirectory to the client, this will make it easier in future to update the javascript libraries the client uses.

There will be associated changes to the wiki-client and wiki packages (*wiki-client and wiki-node repositories*). All three packages will have a minor version change.

### CODE REVIEW

**Comment by opn** [comment]
@paul90 I'd like to be able to do a test of a pure javascript client running from a local file system without a server - or just a plain vanilla http server - how far away are we from being able to do this?

**Comment by paul90** [comment]
Need to include the activity plugin as a devDependency, so the tests are self contained and not relying on having the repo for the activity plugin alongside this one.

**Comment by WardCunningham** [comment]
I understand the motivation for this change and find no fault with the commits so far. I don't feel qualified to merge this to master so I leave this in @paul90's hands.

**Comment by paul90** [comment]
A rainy Sunday, so I'll be completing this today...

**Comment by WardCunningham** [comment]
I will continue to read these commits and note anything that comes to mind but will leave merges to @paul90.

**Comment by paul90** [comment]
Published as + wiki-server@0.6.0

**Pull request merged**
